### PR TITLE
[Audio] Rename current_build to current_version in Config

### PR DESCRIPTION
**Pull request by Tobotimus**
The change introduced in #2201 caused the following traceback for users who hadn't previously loaded audio whilst on 3.0.0rc1.post1.

```py
Exception during loading of cog
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/redbot/core/core_commands.py", line 104, in _load
    await bot.load_extension(spec)
  File "/usr/local/lib/python3.7/dist-packages/redbot/core/bot.py", line 228, in load_extension
    await lib.setup(self)
  File "/usr/local/lib/python3.7/dist-packages/redbot/cogs/audio/__init__.py", line 52, in setup
    await maybe_download_lavalink(bot.loop, cog)
  File "/usr/local/lib/python3.7/dist-packages/redbot/cogs/audio/__init__.py", line 37, in maybe_download_lavalink
    current_build = redbot.core.VersionInfo.from_json(await cog.config.current_build())
  File "/usr/local/lib/python3.7/dist-packages/redbot/core/config.py", line 195, in _get
    return self.nested_update(raw, default)
  File "/usr/local/lib/python3.7/dist-packages/redbot/core/config.py", line 418, in nested_update
    for key, value in current.items():
AttributeError: 'list' object has no attribute 'items'
```

As a fix, I've simply renamed the `current_build` key to `current_version`. This means the `current_version` key will always be a dict and never a list, and `current_build` having no defaults means it won't mess with `[p]audioset settings`.

### CODE REVIEW

**Comment by Tobotimus** [comment]
Also included, is a change to `config.Group.__call__` (and, by extension, `Group.config.all()`) so that the retrieved value is not updated with defaults if it is not a dict.

**Comment by mikeshardmind** [comment]
Can confirm this fixes the issue.

For anyone not content to wait who is impacted:

```
[p]eval
from redbot.core.config import Config
aconfig = Config.get_conf(None, identifier=2711759130, cog_name="Audio")
await aconfig.current_build.clear()
```
Will resolve this for RC1, but requires eval enabled.
